INSERT INTO `gradschool_application_2.0`.`OPTIONS_Country` (`CountryId`, `value`, `title`) 
VALUES 
(NULL,'', 'Select'),
(NULL,'USA', "United States"),
(NULL,'AFG', "Afghanistan"),
(NULL,'ALA', "Aland Islands"),
(NULL,'ALB', "Albania"),
(NULL,'DZA', "Algeria"),
(NULL,'ASM', "American Samoa"),
(NULL,'AND', "Andorra"),
(NULL,'AGO', "Angola"),
(NULL,'AIA', "Anguilla"),
(NULL,'ATA', "Antarctica"),
(NULL,'ATG', "Antigua and Barbuda"),
(NULL,'ARG', "Argentina"),
(NULL,'ARM', "Armenia"),
(NULL,'ABW', "Aruba"),
(NULL,'AUS', "Australia"),
(NULL,'AUT', "Austria"),
(NULL,'AZE', "Azerbaijan"),
(NULL,'BHS', "Bahamas"),
(NULL,'BHR', "Bahrain"),
(NULL,'BGD', "Bangladesh"),
(NULL,'BRB', "Barbados"),
(NULL,'BLR', "Belarus"),
(NULL,'BEL', "Belgium"),
(NULL,'BLZ', "Belize"),
(NULL,'BEN', "Benin"),
(NULL,'BMU', "Bermuda"),
(NULL,'BTN', "Bhutan"),
(NULL,'BOL', "Bolivia"),
(NULL,'BIH', "Bosnia and Herzegovina"),
(NULL,'BWA', "Botswana"),
(NULL,'BVT', "Bouvet Island"),
(NULL,'BRA', "Brazil"),
(NULL,'IOT', "British Indian Ocean Territory"),
(NULL,'BRN', "Brunei Darussalam"),
(NULL,'BGR', "Bulgaria"),
(NULL,'BFA', "Burkina Faso"),
(NULL,'BDI', "Burundi"),
(NULL,'KHM', "Cambodia"),
(NULL,'CMR', "Cameroon"),
(NULL,'CAN', "Canada"),
(NULL,'CPV', "Cape Verde"),
(NULL,'CYM', "Cayman Islands"),
(NULL,'CAF', "Central African Republic"),
(NULL,'TCD', "Chad"),
(NULL,'CHL', "Chile"),
(NULL,'CHN', "China"),
(NULL,'CXR', "Christmas Island"),
(NULL,'CCK', "Cocos (Keeling) Islands"),
(NULL,'COL', "Colombia"),
(NULL,'COM', "Comoros"),
(NULL,'COD', "Congo"),
(NULL,'COK', "Cook Islands"),
(NULL,'CRI', "Costa Rica"),
(NULL,'CIV', "Cote D`Ivoire"),
(NULL,'HRV', "Croatia"),
(NULL,'CUB', "Cuba"),
(NULL,'CYP', "Cyprus"),
(NULL,'CZE', "Czech Republic"),
(NULL,'DNK', "Denmark"),
(NULL,'DJI', "Djibouti"),
(NULL,'DMA', "Dominica"),
(NULL,'DOM', "Dominican Republic"),
(NULL,'TLS', "East Timor"),
(NULL,'ECU', "Ecuador"),
(NULL,'EGY', "Egypt"),
(NULL,'SLV', "El Salvador"),
(NULL,'GNQ', "Equatorial Guinea"),
(NULL,'ERI', "Eritrea"),
(NULL,'EST', "Estonia"),
(NULL,'ETH', "Ethiopia"),
(NULL,'FLK', "Falkland Islands (Malvinas)"),
(NULL,'FRO', "Faroe Islands"),
(NULL,'FJI', "Fiji"),
(NULL,'FIN', "Finland"),
(NULL,'MKD', "Fmr Yugoslav Rep of Macedonia"),
(NULL,'FRA', "France"),
(NULL,'GUF', "French Guiana"),
(NULL,'PYF', "French Polynesia"),
(NULL,'ATF', "French Southern Territories"),
(NULL,'GAB', "Gabon"),
(NULL,'GMB', "Gambia"),
(NULL,'GEO', "Georgia"),
(NULL,'DEU', "Germany"),
(NULL,'GHA', "Ghana"),
(NULL,'GIB', "Gibraltar"),
(NULL,'GRC', "Greece"),
(NULL,'GRL', "Greenland"),
(NULL,'GRD', "Grenada"),
(NULL,'GLP', "Guadeloupe"),
(NULL,'GUM', "Guam"),
(NULL,'GTM', "Guatemala"),
(NULL,'GGY', "Guernsey"),
(NULL,'GNB', "Guinea-Bissau"),
(NULL,'GIN', "Guinea"),
(NULL,'GUY', "Guyana"),
(NULL,'HTI', "Haiti"),
(NULL,'HMD', "Heard and McDonald Islands"),
(NULL,'VAT', "Holy See (Vatican City State)"),
(NULL,'HND', "Honduras"),
(NULL,'HKG', "Hong Kong"),
(NULL,'HUN', "Hungary"),
(NULL,'ISL', "Iceland"),
(NULL,'IND', "India"),
(NULL,'IDN', "Indonesia"),
(NULL,'IRN', "Iran (Islamic Republic Of)"),
(NULL,'IRQ', "Iraq"),
(NULL,'IRL', "Ireland"),
(NULL,'IMN', "Isle of Man"),
(NULL,'ISR', "Israel"),
(NULL,'ITA', "Italy"),
(NULL,'JAM', "Jamaica"),
(NULL,'JPN', "Japan"),
(NULL,'JEY', "Jersey"),
(NULL,'JOR', "Jordan"),
(NULL,'KAZ', "Kazakhstan"),
(NULL,'KEN', "Kenya"),
(NULL,'KIR', "Kiribati"),
(NULL,'LAO', "Lao People's Democratic Republic"),
(NULL,'KOR', "Korea Republic of"),
(NULL,'KOS', "Kosovo"),
(NULL,'KWT', "Kuwait"),
(NULL,'KGZ', "Kyrgyzstan"),
(NULL,'PRK', "Korea Democratic People's Republic"),
(NULL,'LVA', "Latvia"),
(NULL,'LBN', "Lebanon"),
(NULL,'LSO', "Lesotho"),
(NULL,'LBR', "Liberia"),
(NULL,'LBY', "Libyan Arab Jamahiriya"),
(NULL,'LIE', "Liechtenstein"),
(NULL,'LTU', "Lithuania"),
(NULL,'LUX', "Luxembourg"),
(NULL,'MAC', "Macao"),
(NULL,'MDG', "Madagascar"),
(NULL,'MWI', "Malawi"),
(NULL,'MYS', "Malaysia"),
(NULL,'MDV', "Maldives"),
(NULL,'MLI', "Mali"),
(NULL,'MLT', "Malta"),
(NULL,'MHL', "Marshall Islands"),
(NULL,'MTQ', "Martinique"),
(NULL,'MRT', "Mauritania"),
(NULL,'MUS', "Mauritius"),
(NULL,'MYT', "Mayotte"),
(NULL,'MEX', "Mexico"),
(NULL,'FSM', "Micronesia Federated States"),
(NULL,'MDA', "Moldova Republic of"),
(NULL,'MCO', "Monaco"),
(NULL,'MNG', "Mongolia"),
(NULL,'MSR', "Montserrat"),
(NULL,'MAR', "Morocco"),
(NULL,'MOZ', "Mozambique"),
(NULL,'MMR', "Myanmar"),
(NULL,'NAM', "Namibia"),
(NULL,'NRU', "Nauru"),
(NULL,'NPL', "Nepal"),
(NULL,'ANT', "Netherlands Antilles"),
(NULL,'NLD', "Netherlands"),
(NULL,'NCL', "New Caledonia"),
(NULL,'NZL', "New Zealand"),
(NULL,'NIC', "Nicaragua"),
(NULL,'NER', "Niger"),
(NULL,'NGA', "Nigeria"),
(NULL,'NIU', "Niue"),
(NULL,'NFK', "Norfolk Island"),
(NULL,'MNP', "Northern Mariana Islands"),
(NULL,'NOR', "Norway"),
(NULL,'OMN', "Oman"),
(NULL,'PAK', "Pakistan"),
(NULL,'PLW', "Palau"),
(NULL,'PSE', "Palestinian Territory Occupie"),
(NULL,'PAN', "Panama"),
(NULL,'PNG', "Papua New Guinea"),
(NULL,'PRY', "Paraguay"),
(NULL,'PER', "Peru"),
(NULL,'PHL', "Philippines"),
(NULL,'PCN', "Pitcairn"),
(NULL,'POL', "Poland"),
(NULL,'PRT', "Portugal"),
(NULL,'PRI', "Puerto Rico"),
(NULL,'QAT', "Qatar"),
(NULL,'MNE', "Republic of Montenegro"),
(NULL,'SRB', "Republic of Serbia"),
(NULL,'REU', "Reunion"),
(NULL,'ROU', "Romania"),
(NULL,'RUS', "Russian Federation"),
(NULL,'RWA', "Rwanda"),
(NULL,'BLM', "Saint Barthelemy"),
(NULL,'SHN', "Saint Helena"),
(NULL,'KNA', "Saint Kitts and Nevis"),
(NULL,'LCA', "Saint Lucia"),
(NULL,'MAF', "Saint Martin"),
(NULL,'SPM', "Saint Pierre and Miquelon"),
(NULL,'WSM', "Samoa"),
(NULL,'SMR', "San Marino"),
(NULL,'STP', "Sao Tome and Principe"),
(NULL,'SAU', "Saudi Arabia"),
(NULL,'SEN', "Senegal"),
(NULL,'SMX', "Serbia and Montenegro"),
(NULL,'SYC', "Seychelles"),
(NULL,'SLE', "Sierra Leone"),
(NULL,'SGP', "Singapore"),
(NULL,'SVK', "Slovakia"),
(NULL,'SVN', "Slovenia"),
(NULL,'SLB', "Solomon Islands"),
(NULL,'SOM', "Somalia"),
(NULL,'ZAF', "South Africa"),
(NULL,'ESP', "Spain"),
(NULL,'LKA', "Sri Lanka"),
(NULL,'VCT', "St Vincent and the Grenadines"),
(NULL,'SGS', "South Georgia & South Sandwich Islands"),
(NULL,'SDN', "Sudan"),
(NULL,'SUR', "Suriname"),
(NULL,'SJM', "Svalbard and Jan Mayen"),
(NULL,'SWZ', "Swaziland"),
(NULL,'SWE', "Sweden"),
(NULL,'CHE', "Switzerland"),
(NULL,'SYR', "Syrian Arab Republic"),
(NULL,'TWN', "Taiwan Province of China"),
(NULL,'TJK', "Tajikistan"),
(NULL,'TZA', "Tanzania United Republic of"),
(NULL,'THA', "Thailand"),
(NULL,'TGO', "Togo"),
(NULL,'TKL', "Tokelau"),
(NULL,'TON', "Tonga"),
(NULL,'TTO', "Trinidad and Tobago"),
(NULL,'TUN', "Tunisia"),
(NULL,'TUR', "Turkey"),
(NULL,'TKM', "Turkmenistan"),
(NULL,'TCA', "Turks and Caicos Islands"),
(NULL,'TUV', "Tuvalu"),
(NULL,'UGA', "Uganda"),
(NULL,'UKR', "Ukraine"),
(NULL,'ARE', "United Arab Emirates"),
(NULL,'GBR', "United Kingdom"),
(NULL,'USA', "United States"),
(NULL,'URY', "Uruguay"),
(NULL,'UMI', "US Minor Outlying Islands"),
(NULL,'UZB', "Uzbekistan"),
(NULL,'VUT', "Vanuatu"),
(NULL,'VEN', "Venezuela"),
(NULL,'VNM', "Viet Nam"),
(NULL,'VGB', "Virgin Islands (British)"),
(NULL,'VIR', "Virgin Islands (U.S.)"),
(NULL,'WLF', "Wallis and Futuna Islands"),
(NULL,'ESH', "Western Sahara"),
(NULL,'YEM', "Yemen"),
(NULL,'YUG', "Yugoslavia"),
(NULL,'ZMB', "Zambia"),
(NULL,'ZWE', "Zimbabwe");
