
INSERT INTO `gradschool_application_2.0`.`OPTIONS_State` (`stateId`, `value`, `title`) 
VALUES 
(NULL,'',"Select"),
(NULL,'IT', "International"),
(NULL,'AL', "Alabama"),
(NULL,'AK', "Alaska"),
(NULL,'AZ', "Arizona"),
(NULL,'AR', "Arkansas"),
(NULL,'CA', "California"),
(NULL,'CO', "Colorado"),
(NULL,'CT', "Connecticut"),
(NULL,'DC', "District of Columbia"),
(NULL,'DE', "Delaware"),
(NULL,'FL', "Florida"),
(NULL,'GA', "Georgia"),
(NULL,'HI', "Hawaii"),
(NULL,'ID', "Idaho"),
(NULL,'IL', "Illinois"),
(NULL,'IN', "Indiana"),
(NULL,'IA', "Iowa"),
(NULL,'KS', "Kansas"),
(NULL,'KY', "Kentucky"),
(NULL,'LA', "Louisiana"),
(NULL,'ME', "Maine"),
(NULL,'MD', "Maryland"),
(NULL,'MA', "Massachusetts"),
(NULL,'MI', "Michigan"),
(NULL,'MN', "Minnesota"),
(NULL,'MS', "Mississippi"),
(NULL,'MO', "Missouri"),
(NULL,'MT', "Montana"),
(NULL,'NE', "Nebraska"),
(NULL,'NV', "Nevada"),
(NULL,'NH', "New Hampshire"),
(NULL,'NJ', "New Jersey"),
(NULL,'NM', "New Mexico"),
(NULL,'NY', "New York"),
(NULL,'NC', "North Carolina"),
(NULL,'ND', "North Dakota"),
(NULL,'OH', "Ohio"),
(NULL,'OK', "Oklahoma"),
(NULL,'OR', "Oregon"),
(NULL,'PA', "Pennsylvania"),
(NULL,'RI', "Rhode Island"),
(NULL,'SC', "South Carolina"),
(NULL,'SD', "South Dakota"),
(NULL,'TN', "Tennessee"),
(NULL,'TX', "Texas"),
(NULL,'UT', "Utah"),
(NULL,'VT', "Vermont"),
(NULL,'VA', "Virginia"),
(NULL,'WA', "Washington"),
(NULL,'WV', "West Virginia"),
(NULL,'WI', "Wisconsin"),
(NULL,'WY', "Wyoming"),
(NULL,'AB', "Alberta"),
(NULL,'BC', "British Columbia"),
(NULL,'MB', "Manitoba"),
(NULL,'NB', "New Brunswick"),
(NULL,'NL', "Newfoundland and Labrador"),
(NULL,'NS', "Nova Scotia"),
(NULL,'ON', "Ontario"),
(NULL,'PE', "Prince Edward Island"),
(NULL,'QC', "Quebec"),
(NULL,'SK', "Saskatchewan"),
(NULL,'NT', "Northwest Territories"),
(NULL,'NU', "Nunavut"),
(NULL,'YT', "Yukon");
